#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

output=$(python "$DIR"/apicreds.py "$@")
if [[ "$output" =~ ^export.* ]]; then
  $output
  unset AWS_SESSION_TOKEN
else
  echo "$output"
fi
