#!/usr/bin/env bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

source "${DIR}/venv/bin/activate"

output=$(python "$DIR"/apicreds.py "$@")
if [[ "$output" =~ ^export.* ]]; then
  $output
  unset AWS_SESSION_TOKEN
else
  echo "$output"
fi
